export default {
  SUCCESS_COLOR: '#21B017',
  DELETE_COLOR: 'red',
  WHITE_COLOR: '#fff',

  LIGHT_BACKGROUND_COLOR: '#FFF69C',
  LIGHT_SUCCESS_ALERT_BG: 'rgba(255, 117, 120, 0.9)',
  LIGHT_MAIN_COLOR: '#362EFF',
  LIGHT_NB_GREY_COLOR: 'coolGray.800',
  LIGHT_PLACEHOLDER_COLOR: '#618EFF',
  LIGHT_BORDER_COLOR: '#999',
  LIGHT_CANCEL_COLOR: '#999',
  LIGHT_LIST_ITEM_BG: '#fff',
  LIGHT_MODAL_BG: '#fff',
  LIGHT_BUTTON_COLOR: '#362EFF',
  LIGHT_TAB_BAR_BG: '#fff',

  DARK_BACKGROUND_COLOR: '#5468ff',
  DARK_PLACEHOLDER_COLOR: '#eeeeee',
  DARK_LIST_ITEM_BG: '#666',
  DARK_MAIN_COLOR: '#eeeeee',
  DARK_MODAL_BG: '#666',
  DARK_BUTTON_COLOR: '#fff',
  DARK_TAB_BAR_BG: '#666',
  DARK_CANCEL_COLOR: '#000',

  ICON_MED_SIZE: 50,
  ICON_SM_SIZE: 40,
  ICON_EXSM_SIZE: 25,
  ICON_DEF_COLOR: '#000',
  ICON_ARROW_SIZE: 30,

  SM_FS: 17,
  MAIN_FS: 20,
  ALERT_FS: 23,
  BIG_FS: 35,

  CONTAINER_WD: '75%',
  FULL_WD: '100%',
  MODAL_WD: '400px',

  FLEX_SHRINK: 1,
  SPACE: 2,
  MT: 1,

  DEALY_PRESS: 700,

  HEADER_ICON_SIZE: 20,
  HEADER_COLOR_1: '#362EFF',
  HEADER_COLOR_2: '#ff0000',
  HEADER_COLOR_3: '#dd00ff',
  HEADER_COLOR_4: '#00ab53',
  HEADER_COLOR_5: '#00ab9f',
  HEADER_COLOR_6: '#ff00ae',
  HEADER_COLOR_7: '#000000',

  TAB_BAR_FS: 12,

  HIGH_P_COLOR: 'red',
  NORMAL_P_COLOR: 'orange',
  LOW_P_COLOR: 'green',
};
